.TH CSWM 1
.SH DESCRIPTION
cswm is a minimalist tiling window manager.  New windows are placed in a
large master area; other windows are placed in the stacking area but
can be swapped back to the master area.
.SH USAGE
.TP
.B ALT-SHIFT-T/W/L
Start terminal, start web browser, or lock screen, respectively.
.TP
.B ALT-TAB/J/K
Focus next/next/previous window.
.TP
.B ALT-H/L
Resize the master area.
.TP
.B ALT-RETURN
Swap focused window between master and stacking area.
.TP
.B ALT-SHIFT-C/Q
Close focused window and quit, respectively.
