.TH CSWM 1
.SH DESCRIPTION
cswm is a minimalist tiling window manager that splits the screen into
a larger single-window master area and a smaller (by default)
window-stacking area; windows can be swapped between areas.  All window
manipulation is done via keyboard.
.SH USAGE
.TP
.B ALT-SHIFT-T/W/L
Start terminal, start web browser, or lock screen, respectively.
.TP
.B ALT-TAB/J/K
Focus next/next/previous window.
.TP
.B ALT-H/L
Resize the master area.
.TP
.B ALT-RETURN
Swap focused window between master and stacking area.
.TP
.B ALT-SHIFT-C/Q
Close focused window and quit, respectively.
